Working on clilog for AUR

diff --git a/bin/clilog b/bin/clilog
--- a/bin/clilog
+++ b/bin/clilog
@@ -2,13 +2,17 @@
 
 set -euo pipefail
 
-if [[ ! -f "/usr/local/lib/clilog/functions.sh" ]]; then
-	echo "Error: Clilog is not installed yet, run the script install.sh for installation."
+if [[ -f "/usr/lib/clilog/functions.sh" ]]; then
+    LIB_PATH="/usr/lib/clilog"
+elif [[ -f "/usr/local/lib/clilog/functions.sh" ]]; then
+    LIB_PATH="/usr/local/lib/clilog"
+else
+    echo "Error: Clilog is not installed yet. Please run the install.sh script or install via AUR/package manager."
+    exit 1
 fi
 
-source "/usr/local/lib/clilog/functions.sh"
-source "$HOME/Projects/clilog/src/interactive.sh"
-
+source "$LIB_PATH/functions.sh"
+source "$LIB_PATH/interactive.sh" 
 COMMAND="${1:-}"
 
 case "$COMMAND" in
